import { useState, type FormEvent } from 'react';
import { Building2, MapPin, Plus } from 'lucide-react';
import { useAppStore } from '../../app/AppStore';
import { Badge, Button, Card, Modal, SectionHeader } from '../../components/ui';

export function PropertiesPage() {
  const store = useAppStore();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: '', address: '', city: '', type: 'Einfamilienhaus', status: 'Akquise' as const, estimatedValue: 0 });
  const submit = (event: FormEvent) => { event.preventDefault(); store.addProperty(form); setOpen(false); };
  return <div className="page-stack"><Card><SectionHeader title="Immobilien" subtitle="Objekte von der Akquise bis zum Verkauf" action={<Button onClick={() => setOpen(true)}><Plus size={17} /> Immobilie</Button>} /><div className="property-grid">{store.properties.map((property) => <article className="property-card" key={property.id}><div className="property-visual"><Building2 size={38} /><Badge tone={property.status === 'Vermarktung' ? 'green' : property.status === 'Bewertung' ? 'gold' : 'neutral'}>{property.status}</Badge></div><div className="property-body"><strong>{property.title}</strong><span><MapPin size={15} /> {property.address}, {property.city}</span><dl><div><dt>Objektart</dt><dd>{property.type}</dd></div><div><dt>Schätzwert</dt><dd>{new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(property.estimatedValue)}</dd></div></dl></div></article>)}</div></Card>{open && <Modal title="Immobilie erfassen" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={submit}><label className="form-span">Bezeichnung<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Adresse<input required value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></label><label>Ort<input required value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} /></label><label>Objektart<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option>Einfamilienhaus</option><option>Eigentumswohnung</option><option>Mehrfamilienhaus</option><option>Grundstück</option></select></label><label>Schätzwert<input type="number" value={form.estimatedValue} onChange={(event) => setForm({ ...form, estimatedValue: Number(event.target.value) })} /></label><div className="form-actions form-span"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Abbrechen</Button><Button type="submit">Speichern</Button></div></form></Modal>}</div>;
}
