import type { CampaignTemplate } from './campaignTypes';

export const campaignTemplates: readonly CampaignTemplate[] = [
  {
    id: 'owner-outreach',
    name: 'Eigentümeransprache',
    objective: 'Vorhandene Eigentümerkontakte mit einem nachvollziehbaren Anlass persönlich qualifizieren.',
    targetGroup: 'Dokumentierte Eigentümerkontakte mit offener oder fehlender nächster Aktion',
    recommendedSegments: ['Kernfestung', 'Hochpreis', 'Volumenmaschine'],
    recommendedChannel: 'Telefon',
    durationDays: 5,
    tasks: ['Zielgruppe anhand vorhandener Rollen prüfen', 'Individuellen Gesprächsanlass dokumentieren', 'Einzelkontakte priorisieren', 'Ergebnis und nächste Aktion nach jedem Gespräch festhalten'],
    successCriteria: ['Anteil erreichter Zielkontakte', 'Dokumentierte nächste Aktionen', 'Qualifizierte Bewertungs- oder Gesprächstermine'],
    exclusionCriteria: ['Keine dokumentierte Einwilligung für den gewählten Kanal', 'Aktiver Widerspruch', 'Unvollständige oder ungeprüfte Kontaktdaten', 'Kein nachvollziehbarer Gesprächsanlass'],
    risks: ['Unpersönliche Serienansprache', 'Veraltete Eigentümerrolle', 'Zu hohe Frequenz ohne Mehrwert'],
    legalNotes: ['Kontaktweg und Rechtsgrundlage vor jeder Ansprache individuell prüfen.', 'Keine automatische Empfängerliste oder Versandfreigabe erzeugen.'],
  },
  {
    id: 'referral',
    name: 'Empfehlungsaktion',
    objective: 'Bestehende Beziehungen gezielt um Hinweise oder persönliche Empfehlungen bitten.',
    targetGroup: 'Tippgeber, Netzwerkpartner, Bestandskunden und belastbare Beziehungskontakte',
    recommendedSegments: ['Kernfestung', 'Erweiterungsring', 'selektive Bearbeitung'],
    recommendedChannel: 'Telefon',
    durationDays: 7,
    tasks: ['Beziehungsstärke und letzten Kontakt prüfen', 'Konkreten lokalen Anlass vorbereiten', 'Einzelgespräche führen', 'Empfehlung und Folgeaktion dokumentieren'],
    successCriteria: ['Geführte Empfehlungsgespräche', 'Neue qualifizierte Hinweise', 'Vereinbarte Folgekontakte'],
    exclusionCriteria: ['Kontaktbeziehung ungeklärt', 'Offene Beschwerde oder Widerspruch', 'Kein persönlicher Kontext'],
    risks: ['Zu frühe Empfehlungsfrage', 'Unklare Gegenleistung', 'Fehlende Nachverfolgung'],
    legalNotes: ['Keine verdeckte Vergütungszusage machen.', 'Personenbezogene Daten empfohlener Dritter erst nach zulässiger Übermittlung verarbeiten.'],
  },
  {
    id: 'neighborhood',
    name: 'Nachbarschaftskampagne',
    objective: 'Eine vorhandene Immobilie als lokalen Gesprächsanlass für individuelle Nachbarschaftskontakte nutzen.',
    targetGroup: 'Bestehende Kontakte im Gebiet mit nachvollziehbarem Bezug zum Objektumfeld',
    recommendedSegments: ['Kernfestung', 'Volumenmaschine', 'Hochpreis'],
    recommendedChannel: 'Brief',
    durationDays: 10,
    tasks: ['Objektstatus und zulässige Kommunikationsinhalte prüfen', 'Gebietsbezug vorhandener Kontakte validieren', 'Einzelmaßnahmen vorbereiten', 'Reaktionen und Folgeaktionen dokumentieren'],
    successCriteria: ['Qualifizierte Rückmeldungen', 'Neue Eigentümergespräche', 'Empfehlungen aus dem direkten Umfeld'],
    exclusionCriteria: ['Kein aktives Objekt', 'Objektbezug nicht belegbar', 'Ungeprüfte Adressdaten', 'Widerspruch gegen Ansprache'],
    risks: ['Offenlegung vertraulicher Objektdaten', 'Zu breite Streuung', 'Unklarer lokaler Nutzen'],
    legalNotes: ['Objekt- und Eigentümerdaten nur im freigegebenen Umfang verwenden.', 'Werbliche Ansprache und Datenschutz vor Durchführung prüfen.'],
  },
  {
    id: 'valuation',
    name: 'Bewertungsaktion',
    objective: 'Dokumentierte Bewertungschancen strukturiert in qualifizierte Gespräche überführen.',
    targetGroup: 'Eigentümerkontakte oder Immobilien mit nachvollziehbarem Bewertungsanlass',
    recommendedSegments: ['Kernfestung', 'Hochpreis', 'Volumenmaschine'],
    recommendedChannel: 'Telefon',
    durationDays: 7,
    tasks: ['Bewertungsanlass und Datenlage prüfen', 'Fehlende Objektinformationen identifizieren', 'Individuelle Kontaktaufnahme planen', 'Termin oder nächste Aktion dokumentieren'],
    successCriteria: ['Vollständig qualifizierte Bewertungschancen', 'Vereinbarte Bewertungstermine', 'Geschlossene Datenlücken'],
    exclusionCriteria: ['Kein dokumentierter Eigentümer- oder Objektbezug', 'Fehlende Kontaktfreigabe', 'Unklarer Bewertungsanlass'],
    risks: ['Bewertungsversprechen ohne Datengrundlage', 'Verwechslung interner Arbeitswerte mit Marktwerten'],
    legalNotes: ['Keine Marktwerte oder Genauigkeit suggerieren, die nicht durch Daten und Verfahren belegt sind.', 'Jede Bewertung bleibt ein separater fachlicher Prozess.'],
  },
  {
    id: 'reactivation',
    name: 'Reaktivierung',
    objective: 'Länger unbearbeitete Bestandskontakte mit einem individuellen und relevanten Anlass erneut ansprechen.',
    targetGroup: 'Kontakte ohne aktuelle Aktivität oder dokumentierte nächste Aktion',
    recommendedSegments: ['Erweiterungsring', 'selektive Bearbeitung', 'Volumenmaschine'],
    recommendedChannel: 'Telefon',
    durationDays: 5,
    tasks: ['Letzte Interaktion und Notizen prüfen', 'Reaktivierungsgrund festlegen', 'Kontakte einzeln priorisieren', 'Aktualität der Daten und nächste Aktion dokumentieren'],
    successCriteria: ['Reaktivierte Kontakte', 'Aktualisierte Kontaktdaten', 'Neu vereinbarte Folgeaktionen'],
    exclusionCriteria: ['Aktiver Widerspruch', 'Kein plausibler Anlass', 'Ungeklärte Identität oder Kontaktdaten'],
    risks: ['Kontakt ohne Mehrwert', 'Ignorieren früherer Einwände', 'Zu hohe Wiederholungsfrequenz'],
    legalNotes: ['Frühere Einwände und Kontaktpräferenzen verbindlich berücksichtigen.', 'Keine automatisierte Wiederansprache.'],
  },
  {
    id: 'network',
    name: 'Netzwerkpflege',
    objective: 'Lokale Multiplikatoren und Tippgeber systematisch, persönlich und anlassbezogen pflegen.',
    targetGroup: 'Netzwerk- und Tippgeberkontakte im Zielgebiet',
    recommendedSegments: ['Kernfestung', 'Erweiterungsring', 'selektive Bearbeitung'],
    recommendedChannel: 'Netzwerktermin',
    durationDays: 14,
    tasks: ['Relevante Netzwerkpartner auswählen', 'Gemeinsamen lokalen Gesprächsanlass definieren', 'Termine einzeln vereinbaren', 'Nutzen, Hinweise und nächste Schritte dokumentieren'],
    successCriteria: ['Qualifizierte Netzwerkgespräche', 'Neue lokale Informationen', 'Konkrete Empfehlungen oder Kooperationen'],
    exclusionCriteria: ['Kein lokaler oder fachlicher Bezug', 'Ungeklärte Interessenkonflikte'],
    risks: ['Kontaktpflege ohne konkreten Nutzen', 'Einseitige Erwartungshaltung'],
    legalNotes: ['Kooperations- und Vergütungsmodelle transparent und separat prüfen.', 'Keine Daten Dritter ohne zulässige Grundlage übernehmen.'],
  },
  {
    id: 'market-information',
    name: 'Lokale Marktinformation',
    objective: 'Verifizierte lokale Marktdaten in eine sachliche, klar eingeordnete Einzelkommunikation übersetzen.',
    targetGroup: 'Bestehende Kontakte mit dokumentiertem lokalen Informationsinteresse',
    recommendedSegments: ['Kernfestung', 'Volumenmaschine', 'Hochpreis', 'Erweiterungsring'],
    recommendedChannel: 'E-Mail einzeln',
    durationDays: 10,
    tasks: ['Quellenstatus und Zeitraum prüfen', 'Aussagen auf belegte Daten begrenzen', 'Zielkontakte individuell auswählen', 'Rückfragen und Folgeaktionen dokumentieren'],
    successCriteria: ['Qualifizierte Rückfragen', 'Vereinbarte Markt- oder Bewertungsgespräche', 'Keine ungeklärten Quellenangaben'],
    exclusionCriteria: ['Fehlende oder ungeprüfte Marktdaten', 'Kein dokumentiertes Informationsinteresse', 'Veraltete Quelle'],
    risks: ['Scheingenauigkeit', 'Vermischung unterschiedlicher Zeiträume', 'Unbelegte Marktbehauptungen'],
    legalNotes: ['Quelle, Zeitraum und Genauigkeitsgrenzen sichtbar angeben.', 'Keine automatischen rechtlichen oder fachlichen Freigaben.'],
  },
  {
    id: 'existing-customer',
    name: 'Bestandskundenpflege',
    objective: 'Abgeschlossene Beziehungen mit relevantem Anlass weiter pflegen und Empfehlungspotenzial sichern.',
    targetGroup: 'Kontakte mit abgeschlossenem Vorgang oder verkaufter Immobilie',
    recommendedSegments: ['Kernfestung', 'Hochpreis', 'Erweiterungsring'],
    recommendedChannel: 'Telefon',
    durationDays: 7,
    tasks: ['Abschlussstatus und letzte Interaktion prüfen', 'Passenden Service- oder Jahrestagsanlass wählen', 'Einzelkontakt durchführen', 'Feedback und nächste Beziehungspflege dokumentieren'],
    successCriteria: ['Geführte Bestandskundengespräche', 'Aktualisierte Beziehungshinweise', 'Qualifizierte Empfehlungen'],
    exclusionCriteria: ['Offene Reklamation', 'Kein Abschlussbezug', 'Aktiver Widerspruch'],
    risks: ['Verkaufsdruck nach Abschluss', 'Unpassender Kontaktzeitpunkt'],
    legalNotes: ['Kontaktpräferenzen und Zweckbindung beachten.', 'Empfehlungsfragen nicht mit unklaren Gegenleistungen verbinden.'],
  },
];
