import type { TrainingScenario, TrainingScenarioId } from './types';

export const trainingScenarios: TrainingScenario[] = [
  {
    id: 'owner_first_contact',
    order: 1,
    title: 'Erstkontakt Eigentümer',
    category: 'owner_acquisition',
    difficulty: 1,
    openingSituation: 'Du rufst eine Eigentümerin erstmals an. Es gibt einen sachlichen regionalen Anlass, aber noch keine bestätigte Verkaufsabsicht.',
    partnerProfile: 'Höflich, zeitlich knapp und zunächst zurückhaltend. Sie reagiert positiv auf klare, respektvolle Fragen.',
    primaryGoal: 'Ein qualifiziertes Folgegespräch oder einen Bewertungstermin vorbereiten.',
    minimumGoal: 'Erlaubnis für einen konkreten späteren Kontakt und einen nachvollziehbaren Anlass sichern.',
    objections: ['Ich habe gerade wenig Zeit.', 'Woher haben Sie meine Nummer?', 'Ich möchte nichts verkaufen.'],
    allowedFacts: ['Der regionale Markt ist dein Arbeitsgebiet.', 'Es besteht noch keine bestätigte Verkaufsabsicht.', 'Der Kontakt ist ein anonymisiertes Trainingsprofil.'],
    unknownFacts: ['Immobilienwert', 'Verkaufszeitpunkt', 'Motivation', 'Familien- oder Finanzsituation'],
    successCriteria: ['Erlaubnisorientierter Einstieg', 'Mindestens zwei offene Fragen', 'Keine unterstellte Verkaufsabsicht', 'Konkreter nächster Schritt'],
    failureCriteria: ['Druck oder künstliche Dringlichkeit', 'Erfundener Immobilienwert', 'Monolog ohne Bedarfsermittlung', 'Kein vereinbarter nächster Schritt'],
    quickReplies: ['Passt es für zwei kurze Fragen?', 'Was wäre Ihnen bei einer späteren Bewertung wichtig?', 'Wann darf ich mich sinnvoll noch einmal melden?'],
  },
  {
    id: 'private_sale_attempt',
    order: 2,
    title: 'Privater Verkaufsversuch',
    category: 'owner_acquisition',
    difficulty: 2,
    openingSituation: 'Ein Eigentümer bietet seine Immobilie selbst an und möchte zunächst ohne Makler verkaufen.',
    partnerProfile: 'Selbstbewusst, kostenbewusst und gut vorbereitet. Er erwartet konkrete Fragen statt pauschaler Maklerargumente.',
    primaryGoal: 'Risiken und Prioritäten des privaten Verkaufs verstehen und einen hilfreichen Folgetermin anbieten.',
    minimumGoal: 'Erlaubnis für einen späteren Rückruf nach den ersten Vermarktungserfahrungen erhalten.',
    objections: ['Das kann ich selbst.', 'Ich möchte Provision sparen.', 'Ich habe bereits viele Anfragen.'],
    allowedFacts: ['Die Immobilie wird privat angeboten.', 'Der Eigentümer möchte zunächst ohne Makler starten.', 'Die Qualität der Anfragen ist unbekannt.'],
    unknownFacts: ['Anzahl qualifizierter Interessenten', 'Preisstrategie', 'Unterlagenstatus', 'Zeitdruck'],
    successCriteria: ['Respekt für den Eigenversuch', 'Fragen zu Aufwand, Auswahl und Sicherheit', 'Nutzen erst nach Bedarfsermittlung', 'Realistischer Folgetermin'],
    failureCriteria: ['Privatverkauf abwerten', 'Scheitern vorhersagen', 'Höchstpreis versprechen', 'Provision rechtfertigen, bevor Bedarf geklärt ist'],
    quickReplies: ['Was funktioniert bisher bereits gut?', 'Wie prüfen Sie die Bonität der Interessenten?', 'Soll ich mich nach den ersten Besichtigungen noch einmal melden?'],
  },
  {
    id: 'commission_objection',
    order: 3,
    title: 'Provisions-Einwand',
    category: 'objection_handling',
    difficulty: 3,
    openingSituation: 'Im Eigentümergespräch wird die Provision als zu hoch bezeichnet.',
    partnerProfile: 'Analytisch, preisorientiert und skeptisch gegenüber allgemeinen Qualitätsversprechen.',
    primaryGoal: 'Den Einwand präzisieren und den wirtschaftlichen sowie operativen Nutzen nachvollziehbar einordnen.',
    minimumGoal: 'Verstehen, welcher Teil der Leistung oder Vergütung konkret nicht überzeugt.',
    objections: ['Andere sind günstiger.', 'Warum sollte ich dafür so viel zahlen?', 'Dann verkaufe ich lieber selbst.'],
    allowedFacts: ['Die konkrete Leistung muss transparent erklärt werden.', 'Es darf keine erfundene Vergleichsprovision genannt werden.', 'Verhandlungsspielräume sind nicht vorgegeben.'],
    unknownFacts: ['Budgetgrenze', 'Angebote anderer Makler', 'Entscheidungskriterien', 'Verhandlungsbereitschaft'],
    successCriteria: ['Einwand anerkennen', 'Mit Rückfrage konkretisieren', 'Leistung am Bedarf ausrichten', 'Keine Preisgarantie'],
    failureCriteria: ['Einwand wegdiskutieren', 'Wettbewerber schlechtreden', 'Unzulässige Garantie', 'Sofortrabatt ohne Klärung'],
    quickReplies: ['Welcher Teil der Vergütung ist für Sie nicht nachvollziehbar?', 'Welche Leistung müsste den Aufwand für Sie rechtfertigen?', 'Darf ich Ihnen den Ablauf transparent gegenüberstellen?'],
  },
  {
    id: 'existing_agent',
    order: 4,
    title: 'Bestehender Makler',
    category: 'objection_handling',
    difficulty: 3,
    openingSituation: 'Der Eigentümer erklärt, bereits mit einem anderen Makler zusammenzuarbeiten.',
    partnerProfile: 'Loyal, vorsichtig und sensibel für respektloses Verhalten gegenüber dem bestehenden Ansprechpartner.',
    primaryGoal: 'Die bestehende Zusammenarbeit respektieren und einen zulässigen späteren Kontaktpunkt vereinbaren.',
    minimumGoal: 'Status, Laufzeit und Zufriedenheit nur soweit freiwillig klären, ohne Abwerbung oder Druck.',
    objections: ['Wir haben schon einen Makler.', 'Ich möchte keinen zweiten Ansprechpartner.', 'Der Vertrag läuft noch.'],
    allowedFacts: ['Es besteht eine Maklerbeziehung.', 'Vertragsinhalte und Laufzeit sind unbekannt.', 'Der bestehende Makler darf nicht abgewertet werden.'],
    unknownFacts: ['Vertragsart', 'Vertragsende', 'Zufriedenheit', 'Vermarktungsergebnis'],
    successCriteria: ['Bestehende Beziehung respektieren', 'Keine Rechtsberatung', 'Erlaubnis für späteren Kontakt', 'Sauberer Gesprächsabschluss'],
    failureCriteria: ['Vertragsbruch empfehlen', 'Wettbewerber abwerten', 'Rechtslage behaupten', 'Ungefragtes Nachfassen'],
    quickReplies: ['Das respektiere ich selbstverständlich.', 'Wann wäre ein neutraler Rückkontakt für Sie in Ordnung?', 'Gibt es etwas, das Ihnen in der Zusammenarbeit besonders wichtig ist?'],
  },
  {
    id: 'nonbinding_valuation',
    order: 5,
    title: 'Unverbindliche Bewertung',
    category: 'appointment',
    difficulty: 2,
    openingSituation: 'Eine Eigentümerin interessiert sich für eine unverbindliche Einschätzung, ohne einen Verkauf zugesagt zu haben.',
    partnerProfile: 'Informationsorientiert, vorsichtig und offen, solange keine versteckte Abschlussabsicht entsteht.',
    primaryGoal: 'Einen transparenten Bewertungstermin mit klarer Erwartungshaltung vereinbaren.',
    minimumGoal: 'Benötigte Informationen und Entscheidungsrahmen für eine seriöse Bewertung klären.',
    objections: ['Ich möchte wirklich nur den Wert wissen.', 'Ich entscheide noch lange nicht.', 'Ist das wirklich unverbindlich?'],
    allowedFacts: ['Es gibt Interesse an einer Bewertung.', 'Ein Verkauf ist nicht bestätigt.', 'Eine belastbare Bewertung benötigt Objektinformationen.'],
    unknownFacts: ['Verkaufsabsicht', 'Zeithorizont', 'Objektzustand', 'Unterlagenlage'],
    successCriteria: ['Unverbindlichkeit sauber erklären', 'Bewertungsgrundlage klären', 'Termin mit Ziel und Vorbereitung', 'Keine Verkaufsunterstellung'],
    failureCriteria: ['Bewertung ohne Daten versprechen', 'Verkauf als sicher darstellen', 'Versteckte Bindung', 'Wertspanne erfinden'],
    quickReplies: ['Welche Frage soll die Bewertung für Sie beantworten?', 'Welche Unterlagen liegen bereits vor?', 'Welcher Termin passt für eine saubere Vor-Ort-Aufnahme?'],
  },
  {
    id: 'no_current_sale_intent',
    order: 6,
    title: 'Kein aktueller Verkaufswunsch',
    category: 'owner_acquisition',
    difficulty: 2,
    openingSituation: 'Der Gesprächspartner stellt klar, aktuell nicht verkaufen zu wollen.',
    partnerProfile: 'Freundlich, aber klar. Er akzeptiert nur einen Kontakt, wenn dieser einen echten zukünftigen Nutzen hat.',
    primaryGoal: 'Einen freiwilligen, anlassbezogenen langfristigen Kontakt etablieren.',
    minimumGoal: 'Klären, ob und wann ein späterer Markt- oder Bewertungsimpuls erwünscht ist.',
    objections: ['Verkauf ist kein Thema.', 'Vielleicht irgendwann, aber nicht jetzt.', 'Bitte keine regelmäßigen Anrufe.'],
    allowedFacts: ['Aktuell besteht kein Verkaufswunsch.', 'Ein späterer Bedarf ist offen.', 'Kontaktfrequenz muss freiwillig vereinbart werden.'],
    unknownFacts: ['Langfristiger Zeithorizont', 'Auslöser für einen Verkauf', 'Bevorzugter Kanal', 'Informationsinteressen'],
    successCriteria: ['Nein akzeptieren', 'Optionalen Nutzen anbieten', 'Kontaktkanal und Anlass klären', 'Keine Kontaktserie aufzwingen'],
    failureCriteria: ['Einwand ignorieren', 'Druck durch Marktangst', 'Ungefragte Wiedervorlage', 'Verkaufsabsicht unterstellen'],
    quickReplies: ['Verstanden, dann dränge ich das Thema nicht.', 'Welche Information wäre künftig trotzdem hilfreich?', 'Darf ich mich nur bei einem konkret vereinbarten Anlass melden?'],
  },
  {
    id: 'later_callback',
    order: 7,
    title: 'Späterer Rückruf',
    category: 'appointment',
    difficulty: 1,
    openingSituation: 'Der Kontakt hat gerade keine Zeit und bittet um einen späteren Rückruf.',
    partnerProfile: 'Eilig und knapp. Eine präzise Terminfrage wird geschätzt, weitere Verkaufsthemen jetzt nicht.',
    primaryGoal: 'Einen konkreten Rückrufzeitpunkt mit Anlass vereinbaren.',
    minimumGoal: 'Tag, Zeitfenster und bevorzugte Nummer bestätigen.',
    objections: ['Jetzt wirklich nicht.', 'Rufen Sie irgendwann nächste Woche an.', 'Ich weiß noch nicht, wann ich Zeit habe.'],
    allowedFacts: ['Der Kontakt bittet um späteren Rückruf.', 'Das aktuelle Gespräch soll kurz bleiben.', 'Ein genaues Zeitfenster ist noch offen.'],
    unknownFacts: ['Verfügbarkeit', 'Gesprächsdauer', 'Priorität des Themas', 'Bevorzugter Kanal'],
    successCriteria: ['Zeit respektieren', 'Zwei konkrete Optionen anbieten', 'Anlass kurz bestätigen', 'Rückruf verbindlich zusammenfassen'],
    failureCriteria: ['Gespräch trotzdem fortsetzen', 'Vagen Rückruf akzeptieren', 'Mehrfaches Nachfassen ankündigen', 'Kein Zeitfenster'],
    quickReplies: ['Natürlich. Passt Dienstag 17 Uhr oder Mittwoch 12 Uhr besser?', 'Ich notiere den Rückruf nur für den vereinbarten Zeitpunkt.', 'Soll der Rückruf maximal zehn Minuten dauern?'],
  },
  {
    id: 'difficult_contact',
    order: 8,
    title: 'Schwieriger Gesprächspartner',
    category: 'objection_handling',
    difficulty: 5,
    openingSituation: 'Ein Eigentümer reagiert gereizt, unterbricht häufig und stellt deine Kompetenz infrage.',
    partnerProfile: 'Konfrontativ, ungeduldig und sehr direkt. Er prüft Ruhe, Klarheit und Grenzen.',
    primaryGoal: 'Gespräch deeskalieren, Kernanliegen verstehen und nur bei gegenseitigem Respekt fortsetzen.',
    minimumGoal: 'Ruhig eine klare Frage stellen oder das Gespräch professionell beenden.',
    objections: ['Sie Makler erzählen doch alle dasselbe.', 'Sie haben keine Ahnung von meiner Immobilie.', 'Verschwenden Sie nicht meine Zeit.'],
    allowedFacts: ['Der Gesprächspartner ist gereizt.', 'Es liegen keine objektspezifischen Fakten vor.', 'Ein professioneller Abbruch ist zulässig.'],
    unknownFacts: ['Grund der Gereiztheit', 'Bisherige Erfahrungen', 'Verkaufsabsicht', 'Objektdaten'],
    successCriteria: ['Ruhige Sprache', 'Keine Gegenaggression', 'Grenzen setzen', 'Eine präzise Klärungsfrage oder sauberer Abbruch'],
    failureCriteria: ['Sarkasmus', 'Drohung', 'Rechthaberei', 'Erfundene Kompetenzbelege'],
    quickReplies: ['Ich höre, dass Sie schlechte Erfahrungen gemacht haben.', 'Welche konkrete Aussage möchten Sie zuerst geklärt haben?', 'Unter diesen Bedingungen beenden wir das Gespräch respektvoll.'],
  },
  {
    id: 'appointment_booking',
    order: 9,
    title: 'Terminvereinbarung',
    category: 'appointment',
    difficulty: 2,
    openingSituation: 'Der Bedarf ist grundsätzlich vorhanden, aber ein konkreter Termin wurde noch nicht vereinbart.',
    partnerProfile: 'Interessiert, jedoch unverbindlich. Er braucht einen klaren Nutzen und wenig organisatorischen Aufwand.',
    primaryGoal: 'Einen konkreten Termin mit Zweck, Dauer und Vorbereitung vereinbaren.',
    minimumGoal: 'Zwei verbindliche Terminoptionen und das Entscheidungsziel festhalten.',
    objections: ['Schicken Sie erst einmal Informationen.', 'Ich muss in den Kalender schauen.', 'Wir können uns später melden.'],
    allowedFacts: ['Grundsätzliches Interesse besteht.', 'Termin und Dauer sind offen.', 'Benötigte Unterlagen sind noch nicht vollständig geklärt.'],
    unknownFacts: ['Verfügbarkeit', 'Teilnehmende', 'Ort', 'Entscheidungsfrist'],
    successCriteria: ['Terminnutzen benennen', 'Konkrete Optionen', 'Vorbereitung klären', 'Termin zusammenfassen'],
    failureCriteria: ['Nur Informationsversand ohne nächsten Schritt', 'Vager Termin', 'Dauer verschweigen', 'Ungeklärtes Ziel'],
    quickReplies: ['Damit Sie danach eine belastbare Entscheidungsgrundlage haben, schlage ich zwei Termine vor.', 'Passt Donnerstag 18 Uhr oder Samstag 10 Uhr?', 'Welche Unterlagen sollen wir vorab prüfen?'],
  },
  {
    id: 'closing_question',
    order: 10,
    title: 'Abschlussfrage',
    category: 'closing',
    difficulty: 4,
    openingSituation: 'Ein ausführliches Eigentümergespräch ist positiv verlaufen. Die Entscheidung zum nächsten Schritt ist noch offen.',
    partnerProfile: 'Grundsätzlich überzeugt, aber entscheidungsvorsichtig. Er reagiert schlecht auf Druck und gut auf klare Zusammenfassungen.',
    primaryGoal: 'Eine klare, faire Abschlussfrage zum vereinbarten nächsten Schritt stellen.',
    minimumGoal: 'Offene Entscheidungshürde benennen und einen konkreten Entscheidungsprozess vereinbaren.',
    objections: ['Ich möchte noch darüber schlafen.', 'Wir sprechen noch mit jemand anderem.', 'Ich bin noch nicht ganz sicher.'],
    allowedFacts: ['Das Gespräch verlief grundsätzlich positiv.', 'Eine endgültige Entscheidung liegt nicht vor.', 'Weitere Optionen können geprüft werden.'],
    unknownFacts: ['Entscheidungsdatum', 'Weitere Anbieter', 'Letzte Bedenken', 'Mitentscheider'],
    successCriteria: ['Nutzen zusammenfassen', 'Offene Bedenken erfragen', 'Klare Abschlussfrage', 'Nein oder Bedenkzeit respektieren'],
    failureCriteria: ['Druckschluss', 'Künstliche Verknappung', 'Entscheidung unterstellen', 'Kein nächster Entscheidungstermin'],
    quickReplies: ['Was fehlt Ihnen noch für eine sichere Entscheidung?', 'Wollen wir den besprochenen nächsten Schritt jetzt verbindlich festhalten?', 'Wann treffen wir die Entscheidung gemeinsam wieder auf?'],
  },
  {
    id: 'referral_request',
    order: 11,
    title: 'Empfehlungsanfrage',
    category: 'network',
    difficulty: 3,
    openingSituation: 'Nach einem wertvollen Gespräch möchtest du respektvoll nach einer Empfehlung fragen.',
    partnerProfile: 'Zufrieden, aber vorsichtig mit persönlichen Kontakten. Er empfiehlt nur bei klarem Nutzen und ohne Druck.',
    primaryGoal: 'Eine konkrete, freiwillige Empfehlung oder Erlaubnis für eine Einführung erhalten.',
    minimumGoal: 'Klären, welche Personengruppe von deiner Unterstützung profitieren könnte.',
    objections: ['Mir fällt gerade niemand ein.', 'Ich gebe ungern Kontaktdaten weiter.', 'Ich möchte niemanden bedrängen.'],
    allowedFacts: ['Das vorherige Gespräch war hilfreich.', 'Es besteht kein Anspruch auf eine Empfehlung.', 'Kontaktdaten dürfen nicht ungefragt übernommen werden.'],
    unknownFacts: ['Netzwerk des Kontakts', 'Konkrete empfehlbare Person', 'Einwilligung Dritter', 'Zeitpunkt'],
    successCriteria: ['Nutzenbezug', 'Freiwilligkeit', 'Einführung statt Datenweitergabe bevorzugen', 'Dankbarer Abschluss'],
    failureCriteria: ['Druck', 'Kontaktdaten verlangen', 'Gegenleistung versprechen', 'Ungefragte Kontaktaufnahme'],
    quickReplies: ['Wem könnte eine neutrale Bewertung aktuell helfen?', 'Eine kurze Einführung durch Sie reicht vollkommen.', 'Nur wenn es für Sie und die andere Person passt.'],
  },
  {
    id: 'network_partner',
    order: 12,
    title: 'Netzwerkpartner',
    category: 'network',
    difficulty: 4,
    openingSituation: 'Du sprichst mit einem regionalen Finanzierungspartner über eine mögliche Zusammenarbeit.',
    partnerProfile: 'Geschäftlich, ergebnisorientiert und sensibel für einseitige Empfehlungsmodelle.',
    primaryGoal: 'Einen beidseitigen Nutzen, klare Qualitätskriterien und einen kleinen nächsten Testschritt definieren.',
    minimumGoal: 'Bedarf, Zielgruppe und Voraussetzungen des Partners verstehen.',
    objections: ['Wir haben bereits Maklerkontakte.', 'Was habe ich konkret davon?', 'Ich möchte keine unqualifizierten Empfehlungen.'],
    allowedFacts: ['Der Partner arbeitet regional.', 'Bestehende Maklerkontakte sind möglich.', 'Es gibt noch keine Kooperationsvereinbarung.'],
    unknownFacts: ['Empfehlungsvolumen', 'Interne Compliance', 'Zielkundensegmente', 'Entscheider'],
    successCriteria: ['Partnerbedarf zuerst verstehen', 'Beidseitiger Nutzen', 'Qualitätskriterien', 'Kleiner messbarer nächster Schritt'],
    failureCriteria: ['Einseitige Forderung', 'Exklusivität unterstellen', 'Provisionszusage ohne Grundlage', 'Keine Qualitätsdefinition'],
    quickReplies: ['Welche Empfehlungen sind für Sie wirklich wertvoll?', 'Wie müsste ein Kontakt qualifiziert sein?', 'Wollen wir einen kleinen Testprozess mit klaren Kriterien vereinbaren?'],
  },
];

export function getTrainingScenario(id: TrainingScenarioId): TrainingScenario {
  const scenario = trainingScenarios.find((item) => item.id === id);
  if (!scenario) throw new Error(`Unbekanntes Trainingsszenario: ${id}`);
  return scenario;
}

export function findTrainingScenario(id: string): TrainingScenario | undefined {
  return trainingScenarios.find((item) => item.id === id);
}
